#!/bin/sh
#$ -V
#$ -cwd
#$ -S /bin/bash
#$ -N trin_g_noflag_transrate
#$ -o $JOB_NAME.o$JOB_ID
#$ -e $JOB_NAME.e$JOB_ID
#$ -q omni
#$ -pe sm 24
#$ -P quanah
#$ -l h_rt=48:00:00
#$ -l h_vmem=8G

transrate --assembly /lustre/scratch/sabaty/melanerpes-project/assemblies/trinity_noflag_gonads/Trinity_noflag.fasta, \
--left /lustre/scratch/sabaty/melanerpes-project/transcriptomes/01_filtered_data/M_carolinus_G_LHD1270_R1.fastq.gz,/lustre/scratch/sabaty/melanerpes-project/transcriptomes/01_filtered_data/M_carolinus_G_LHD1274_R1.fastq.gz,/lustre/scratch/sabaty/melanerpes-project/transcriptomes/01_filtered_data/M_carolinus_G_LHD1275_R1.fastq.gz \
--right /lustre/scratch/sabaty/melanerpes-project/transcriptomes/01_filtered_data/M_carolinus_G_LHD1270_R2.fastq.gz,/lustre/scratch/sabaty/melanerpes-project/transcriptomes/01_filtered_data/M_carolinus_G_LHD1274_R2.fastq.gz,/lustre/scratch/sabaty/melanerpes-project/transcriptomes/01_filtered_data/M_carolinus_G_LHD1275_R2.fastq.gz \
--output /lustre/scratch/sabaty/melanerpes-project/assemblies/trinity_noflag_gonads/trinity_noflag_g_transrate/ \
--threads 32 \

